added missing sprites for species names

diff --git a/scripts/imagemagick/extract-single b/scripts/imagemagick/extract-single
--- a/scripts/imagemagick/extract-single
+++ b/scripts/imagemagick/extract-single
@@ -3,16 +3,17 @@
 # It requires ImageMagick
 
 img=$1 # src image
-frame=$2 # GIF frame
-dest=$3 # destination image
+dest=$2 # destination image
+frame=$3 # GIF frame
 _TRIM=1 # Trim empty space of each icon and the final file?
 
 if [ -z "$2" ]; then
-   frame=0
+    echo "Missing destination image file. Aborting."
+    exit 1
 fi
 
 if [ -z "$3" ]; then
-   dest=${img}
+   frame=0
 fi
 
 frame_img="${img}[${frame}]"
